import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJS Youtube Course",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div>
        <Link href="/">Home</Link> &nbsp;|&nbsp;
        <Link href="/about">About</Link> &nbsp;|&nbsp;
        <Link href="/contact">Contact</Link> &nbsp;|&nbsp;
        <Link href="/users">Users</Link>
      </div>
      {children}
    </body>
  </html>
);

export default RootLayout;
